service: try-serverless-framework
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

  vpc:
    securityGroupIds:
      - ${self:custom.otherfile.environment.${self:provider.stage}.LAMBDA_VPC_SECURITY_GROUP}
    subnetIds:
      - ${self:custom.otherfile.environment.${self:provider.stage}.LAMBDA_VPC_SUBNET_ID}

functions:
  hello:
    handler: handler.hello
    environment:
      CONFIG: ${self:custom.otherfile.environment.${self:provider.stage}.CONFIG}

custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./config/dev.yml)}
      prd: ${file(./config/prd.yml)}
