service: try-serverless-framework
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    environment:
      CONFIG: "CONFIGの内容"

custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./config/dev.yml)}
      prd: ${file(./config/prd.yml)}
